before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - binary: dict
    main: ./
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: "checksums.txt"